version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: